### ISSUE TITLE
Code remove attributes with @

### ISSUE THREAD

**Issue by jonnitto** [sitegeist/Sitegeist.Slipstream#6]
With Neos 7.3 it is possible to add attributes with `@` (e.g. `@click`). This is used in some Javascript Frameworks like [AlpineJS](https://alpinejs.dev). If this package is installed, all attributes with `@` get's removed

**Comment by mhsdesign** [comment]
This is because of the php build in `DOMDocument` parser. It only nows about valid html and sadly `@` is in no ways an official standard it is just tolerated by most browsers.

![image](https://user-images.githubusercontent.com/85400359/157701209-5d761dba-1761-4f2a-a69c-42467d499609.png)

https://validator.w3.org/nu/#textarea

https://github.com/sitegeist/Sitegeist.Slipstream/blob/c8ba67e4ba936bfe187a916bc74ea0b989915eb0/Classes/Service/SlipStreamService.php#L41

----

the `DOMDocument` parser cant be adjusted to allow `@`, the only options are:

1: Build a custom HTML parser -> probably much slower and much work.
2: make a string replace before it is handed to the `DOMDocument` parser like: `str_replace('@', '__internal_at__', $content)` and after building the html together again replace again `__internal_at__` to `@` -> i dont know of the performance impact but should be only minimal.

**Comment by jonnitto** [comment]
I made a PR with option 2
